### ISSUE TITLE
Records not working if enigma2 box uses network share as standard record path

### ISSUE THREAD

**Issue by x23piracy** [jdembski/xbmc-addon-vuplus#1]
Hi,

records will not e bdisplayed if enigma2 uses a network share for records.
It's only working properly with /media/hdd/movie (make use of local hdd).

Greetz X23

**Comment by jdembski** [comment]
I will add an option to the addon settings to let the user optionally define the folder which should be used to fetch the movie list...

**Comment by x23piracy** [comment]
Hi,

i thougth that the plugin get the standard record path from the box?
How does it work actually?

**Comment by jdembski** [comment]
I'm calling the webinterface API without any path:

"http://boxip/web/movielist" 

It is possible to define a directory name by calling the interface like this:

"https://boxip/web/movielist?dirname=/mnt/hdd"

As I don't know a way to fetch the default recording foldername from the box the user has to configure the path manually if it is different from the factory defaults :/

**Comment by x23piracy** [comment]
Hi,

http://e2boxip/web/getcurrlocation

gives the standard path used ;)

Check: http://openelec.tv/forum/83-dvb-ss2-support/28164-wip-pvr-client-addon-for-xbmc-for-epg-and-full-control-of-dreambox-and-dbox2?limit=20&start=200#30413

and

http://openelec.tv/forum/83-dvb-ss2-support/28164-wip-pvr-client-addon-for-xbmc-for-epg-and-full-control-of-dreambox-and-dbox2?limit=20&start=180#30408

Greetz X23

**Comment by jdembski** [comment]
Added support for getlocations in 0.1.8

**Comment by x23piracy** [comment]
Hi,

great thank you ;)
